In [58]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """

SELECT b.facid, f.name, strftime('%m',starttime) as month, SUM(slots)
FROM Bookings as b
JOIN Facilities as f
ON f.facid = b.facid
GROUP BY b.facid, month

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', '07', 270)
(0, 'Tennis Court 1', '08', 459)
(0, 'Tennis Court 1', '09', 591)
(1, 'Tennis Court 2', '07', 207)
(1, 'Tennis Court 2', '08', 483)
(1, 'Tennis Court 2', '09', 588)
(2, 'Badminton Court', '07', 180)
(2, 'Badminton Court', '08', 459)
(2, 'Badminton Court', '09', 570)
(3, 'Table Tennis', '07', 104)
(3, 'Table Tennis', '08', 304)
(3, 'Table Tennis', '09', 422)
(4, 'Massage Room 1', '07', 264)
(4, 'Massage Room 1', '08', 492)
(4, 'Massage Room 1', '09', 648)
(5, 'Massage Room 2', '07', 24)
(5, 'Massage Room 2', '08', 82)
(5, 'Massage Room 2', '09', 122)
(6, 'Squash Court', '07', 164)
(6, 'Squash Court', '08', 400)
(6, 'Squash Court', '09', 540)
(7, 'Snooker Table', '07', 156)
(7, 'Snooker Table', '08', 326)
(7, 'Snooker Table', '09', 426)
(8, 'Pool Table', '07', 117)
(8, 'Pool Table', '08', 322)
(8, 'Pool Table', '09', 471)